name: macOS CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install LLVM@19
        run: brew install llvm@19 ninja
      - name: Install Python dependencies
        run: pip install lit filecheck==0.0.24
      - name: Build and test
        run: |
          cmake --workflow --preset lightstorm-macos-ci
